'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class jFont
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("jFont.jFont", GetType(jFont).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil 
        '''\cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines100_to_110() As String
            Get
                Return ResourceManager.GetString("lines100_to_110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;ce\cell }\pard \ltrpar\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow5\irowband5\ltrrow
        '''\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 \trftsWidth1\trpaddl108\trpaddr108\trpaddfl3\trpaddfr3\tblind0\tblindtype3 \clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 
        '''\clbrdrb\brdrs\b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines111_to_121() As String
            Get
                Return ResourceManager.GetString("lines111_to_121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\*
        '''\ts11\tsrowd\trftsWidthB3\trpaddl108\trpaddr108\trpaddfl3\trpaddft3\trpaddfb3\trpaddfr3\tblind0\tblindtype3\tscellwidthfts0\tsvertalt\tsbrdrt\tsbrdrl\tsbrdrb\tsbrdrr\tsbrdrdgl\tsbrdrdgr\tsbrdrh\tsbrdrv 
        '''\ql \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch\fcs1 \af0\afs20 \ltrch\fcs0 \fs20\lang1024\langfe1024\cgrid\langnp1024\langfenp1024 \snext11 \ssemihidden Normal Table;}}
        '''{\*\latentstyles\lsdstimax156\lsdlockeddef0}{\*\rsidtbl \rsid9848284\rsid15886290}{\*\g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines12_to_22() As String
            Get
                Return ResourceManager.GetString("lines12_to_22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 
        '''\f1\fs12\insrsid15886290 0x039D\cell &apos;\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;27\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x095D\cell _\cell }{\rtlch\fcs1 \af1\afs12 
        '''\ltrch\fcs0 \f123\fs12 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines122_to_132() As String
            Get
                Return ResourceManager.GetString("lines122_to_132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth378\clshdrawnil \cellx6390\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines133_to_143() As String
            Get
                Return ResourceManager.GetString("lines133_to_143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt
        '''\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines144_to_154() As String
            Get
                Return ResourceManager.GetString("lines144_to_154", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x209D\cell Alt+0209\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;d1\cell }\pard \ltrpar
        '''\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow8\irowband8\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb
        '''\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 \trftsWidth1\trp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines155_to_165() As String
            Get
                Return ResourceManager.GetString("lines155_to_165", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar
        '''\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 0x042D\cell *\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;2a\cell }{\rtlch\fcs1 
        '''\af1\afs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines166_to_176() As String
            Get
                Return ResourceManager.GetString("lines166_to_176", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx4140\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawni [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines177_to_187() As String
            Get
                Return ResourceManager.GetString("lines177_to_187", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx697\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil         ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines188_to_198() As String
            Get
                Return ResourceManager.GetString("lines188_to_198", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;9c\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x212D\cell Alt+0212\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 
        '''\f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;d4\cell }\pard \ltrpar\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow11\irowband11\ltrrow
        '''\ts11\trgaph108\trleft-108\trbrdr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines199_to_209() As String
            Get
                Return ResourceManager.GetString("lines199_to_209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx7431\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 
        '''\f1\fs12\insrs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines210_to_220() As String
            Get
                Return ResourceManager.GetString("lines210_to_220", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines221_to_231() As String
            Get
                Return ResourceManager.GetString("lines221_to_231", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \ltrch\fcs0 \b\f1\fs32\insrsid15886290 {myfontname}
        '''\par }\pard \ltrpar\ql \li0\ri0\nowidctlpar\tx1620\wrapdefault\faauto\rin0\lin0\itap0 {\rtlch\fcs1 \af1\afs17 \ltrch\fcs0 \f1\fs17\insrsid15886290 
        '''\par \ltrrow}\trowd \irow0\irowband0\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 \trftsWidth1\trpaddl108\trpaddr108\trpaddfl3\trpaddfr3\tblind0\tblindtype3 \clvertalt\clbrdrt
        '''\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines23_to_33() As String
            Get
                Return ResourceManager.GetString("lines23_to_33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt
        '''\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines232_to_242() As String
            Get
                Return ResourceManager.GetString("lines232_to_242", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \&apos;9f}{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell }{\ltrch\fcs1 \af1\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290 0}{\rtlch\fcs1 
        '''\af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 x215D\cell Alt+0215\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;d7}{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290\charrsid15886290 \cell 
        '''}\pard \l [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines243_to_253() As String
            Get
                Return ResourceManager.GetString("lines243_to_253", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx6626\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx7431\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines254_to_264() As String
            Get
                Return ResourceManager.GetString("lines254_to_264", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx4140\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawni [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines265_to_275() As String
            Get
                Return ResourceManager.GetString("lines265_to_275", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx697\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil         ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines276_to_286() As String
            Get
                Return ResourceManager.GetString("lines276_to_286", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;a2\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x218D\cell Alt+0218\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 
        '''\f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;da\cell }\pard \ltrpar\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow17\irowband17\ltrrow
        '''\ts11\trgaph108\trleft-108\trbrdr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines287_to_297() As String
            Get
                Return ResourceManager.GetString("lines287_to_297", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx7431\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 
        '''\f1\fs12\insrs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines298_to_308() As String
            Get
                Return ResourceManager.GetString("lines298_to_308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines309_to_319() As String
            Get
                Return ResourceManager.GetString("lines309_to_319", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt
        '''\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines320_to_330() As String
            Get
                Return ResourceManager.GetString("lines320_to_330", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x221D\cell Alt+0221\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;dd\cell }\pard \ltrpar
        '''\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow20\irowband20\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb
        '''\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 \trftsWidth1\t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines331_to_341() As String
            Get
                Return ResourceManager.GetString("lines331_to_341", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx7431\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\pard \ltrpar\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 
        '''0x [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines34_to_44() As String
            Get
                Return ResourceManager.GetString("lines34_to_44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar
        '''\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 0x054D\cell 6\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;36\cell }{\rtlch\fcs1 
        '''\af1\afs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines342_to_352() As String
            Get
                Return ResourceManager.GetString("lines342_to_352", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth378\clshdrawnil \cellx6390\clvertalt\clbrdrt\brdrnone \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrnone \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines353_to_363() As String
            Get
                Return ResourceManager.GetString("lines353_to_363", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil 
        '''\cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines364_to_374() As String
            Get
                Return ResourceManager.GetString("lines364_to_374", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \f123\fs12\insrsid15886290\charrsid15886290 \&apos;e0}{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290\charrsid15886290 \cell }\pard \ltrpar\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {
        '''\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow23\irowband23\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 
        '''\trftsWidth1\trpaddl108\trpaddr108\trpaddfl3\trpaddfr3\tblind0\t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines375_to_385() As String
            Get
                Return ResourceManager.GetString("lines375_to_385", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar
        '''\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 0x057D\cell 9\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;39\cell }{\rtlch\fcs1 
        '''\af1\afs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines386_to_396() As String
            Get
                Return ResourceManager.GetString("lines386_to_396", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth378\clshdrawnil \cellx6390\clvertalt\clbrdrt\brdrnone \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrnone \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines397_to_407() As String
            Get
                Return ResourceManager.GetString("lines397_to_407", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx697\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil         ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines408_to_418() As String
            Get
                Return ResourceManager.GetString("lines408_to_418", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;ab\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x227D\cell Alt+0227\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 
        '''\f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;e3\cell }\pard \ltrpar\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow26\irowband26\ltrrow
        '''\ts11\trgaph108\trleft-108\trbrdr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines419_to_429() As String
            Get
                Return ResourceManager.GetString("lines419_to_429", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx7431\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 
        '''\f1\fs12\insrs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines430_to_440() As String
            Get
                Return ResourceManager.GetString("lines430_to_440", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines441_to_451() As String
            Get
                Return ResourceManager.GetString("lines441_to_451", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines45_to_55() As String
            Get
                Return ResourceManager.GetString("lines45_to_55", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt
        '''\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines452_to_462() As String
            Get
                Return ResourceManager.GetString("lines452_to_462", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x230D\cell Alt+0230\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;e6\cell }\pard \ltrpar
        '''\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow29\irowband29\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb
        '''\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 \trftsWidth1\t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines463_to_473() As String
            Get
                Return ResourceManager.GetString("lines463_to_473", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar
        '''\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 0x063D\cell ?\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;3f\cell }{\rtlch\fcs1 
        '''\af1\afs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines474_to_484() As String
            Get
                Return ResourceManager.GetString("lines474_to_484", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines485_to_495() As String
            Get
                Return ResourceManager.GetString("lines485_to_495", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines496_to_506() As String
            Get
                Return ResourceManager.GetString("lines496_to_506", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;b1\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x233D\cell Alt+0233\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 
        '''\f123\fs12\insrsid15886290\charrsid15886290 \&apos;e9}{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290\charrsid15886290 \cell }\pard \ltrpar\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {
        '''\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\in [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines507_to_517() As String
            Get
                Return ResourceManager.GetString("lines507_to_517", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx6626\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx7431\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines518_to_528() As String
            Get
                Return ResourceManager.GetString("lines518_to_528", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx3736\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx4140\clvertalt\clbrdrt\brdrnone \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawni [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines529_to_539() As String
            Get
                Return ResourceManager.GetString("lines529_to_539", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \ltrch\fcs1 \af1\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290 \trowd \irow34\irowband34\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 
        '''\trftsWidth1\trpaddl108\trpaddr108\trpaddfl3\trpaddfr3\tblind0\tblindtype3 \clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx697\clvertalt\clbrdrt
        '''\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines540_to_550() As String
            Get
                Return ResourceManager.GetString("lines540_to_550", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 0x068D\cell D\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;44\cell }{\rtlch\fcs1 
        '''\af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x124D\cell |\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;7c\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x180D\cell Alt+0180
        '''\cell }{\rt [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines551_to_561() As String
            Get
                Return ResourceManager.GetString("lines551_to_561", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt
        '''\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines56_to_66() As String
            Get
                Return ResourceManager.GetString("lines56_to_66", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth378\clshdrawnil \cellx6390\clvertalt\clbrdrt
        '''\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx6626\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidt [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines562_to_572() As String
            Get
                Return ResourceManager.GetString("lines562_to_572", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil 
        '''\cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines573_to_583() As String
            Get
                Return ResourceManager.GetString("lines573_to_583", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \f123\fs12\insrsid15886290\charrsid15886290 \&apos;ee}{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290\charrsid15886290 \cell }\pard \ltrpar\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {
        '''\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow37\irowband37\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 
        '''\trftsWidth1\trpaddl108\trpaddr108\trpaddfl3\trpaddfr3\tblind0\t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines584_to_594() As String
            Get
                Return ResourceManager.GetString("lines584_to_594", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar
        '''\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 0x071D\cell G\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;47\cell }{\rtlch\fcs1 
        '''\af1\afs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines595_to_605() As String
            Get
                Return ResourceManager.GetString("lines595_to_605", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines606_to_616() As String
            Get
                Return ResourceManager.GetString("lines606_to_616", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt
        '''\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines617_to_627() As String
            Get
                Return ResourceManager.GetString("lines617_to_627", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \af1\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290 0}{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 x185D\cell Alt+0185\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;b9\cell }{\rtlch\fcs1 
        '''\af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x241D\cell Alt+0241\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;f1\cell }\pard \ltrpar
        '''\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faaut [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines628_to_638() As String
            Get
                Return ResourceManager.GetString("lines628_to_638", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx6626\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx7431\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines639_to_649() As String
            Get
                Return ResourceManager.GetString("lines639_to_649", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx3736\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx4140\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines650_to_660() As String
            Get
                Return ResourceManager.GetString("lines650_to_660", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 \trftsWidth1\trpaddl108\trpaddr108\trpaddfl3\trpaddfr3\tblind0\tblindtype3 \clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx697\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines661_to_671() As String
            Get
                Return ResourceManager.GetString("lines661_to_671", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x203D\cell Alt+0203\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;cb\cell }\pard \ltrpar
        '''\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow2\irowband2\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb
        '''\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 \trftsWidth1\trp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines67_to_77() As String
            Get
                Return ResourceManager.GetString("lines67_to_77", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x132D\cell Alt+0132\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;84\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x188D\cell 
        '''Alt+0188\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;bc\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x244D\cell Alt+0244\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 
        '''\f123\fs12\insrsid158 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines672_to_682() As String
            Get
                Return ResourceManager.GetString("lines672_to_682", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth378\clshdrawnil \cellx6390\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil 
        '''\cellx6626\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx7431\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines683_to_693() As String
            Get
                Return ResourceManager.GetString("lines683_to_693", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx3736\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx4140\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines694_to_704() As String
            Get
                Return ResourceManager.GetString("lines694_to_704", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 \trftsWidth1\trpaddl108\trpaddr108\trpaddfl3\trpaddfr3\tblind0\tblindtype3 \clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx697\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines705_to_715() As String
            Get
                Return ResourceManager.GetString("lines705_to_715", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x135D\cell Alt+0135\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;87\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x191D\cell 
        '''Alt+0191\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;bf}{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 
        '''\f1\fs12\insrsid1588629 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines716_to_726() As String
            Get
                Return ResourceManager.GetString("lines716_to_726", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth378\clshdrawnil \cellx6390\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines727_to_737() As String
            Get
                Return ResourceManager.GetString("lines727_to_737", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx1502\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth388\clshdrawnil \cellx1890\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt
        '''\brdrs\brdrw15 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines738_to_748() As String
            Get
                Return ResourceManager.GetString("lines738_to_748", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \&apos;c1}{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell }{\ltrch\fcs1 \af1\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290 0}{\rtlch\fcs1 
        '''\af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 x249D\cell Alt+0249\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;f9}{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290\charrsid15886290 \cell 
        '''}\pard \l [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines749_to_759() As String
            Get
                Return ResourceManager.GetString("lines749_to_759", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cellx6626\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx7431\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr
        '''\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines760_to_770() As String
            Get
                Return ResourceManager.GetString("lines760_to_770", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth236\clshdrawnil \cellx2126\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx2931\clvertalt\clbrdrt
        '''\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx3736\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidt [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines771_to_781() As String
            Get
                Return ResourceManager.GetString("lines771_to_781", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar
        '''\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 0x036D\cell $\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;24\cell }{\rtlch\fcs1 
        '''\af1\afs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines78_to_88() As String
            Get
                Return ResourceManager.GetString("lines78_to_88", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 x251D\cell Alt+0251\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290 \&apos;fb}{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290\charrsid15886290 \cell }\pard \ltrpar
        '''\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow50\irowband50\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb
        '''\brdrs\br [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines782_to_792() As String
            Get
                Return ResourceManager.GetString("lines782_to_792", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar
        '''\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 0x084D\cell T\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;54\cell }{\rtlch\fcs1 
        '''\af1\afs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines793_to_803() As String
            Get
                Return ResourceManager.GetString("lines793_to_803", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx3736\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx4140\clvertalt\clbrdrt\brdrnone \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawni [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines804_to_814() As String
            Get
                Return ResourceManager.GetString("lines804_to_814", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \&apos;fd}{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f1\fs12\lang1025\insrsid15886290\charrsid15886290 \cell }\pard \ltrpar\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 
        '''\trowd \irow52\irowband52\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 \trftsWidth1\trpaddl108\trpaddr108\trpaddfl3\trpaddfr3\tblind0\tblindtype3 \clvertalt\clbrdrt
        '''\brdrs\brdrw15  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines815_to_825() As String
            Get
                Return ResourceManager.GetString("lines815_to_825", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 
        '''\f1\fs12\insrsid15886290 0x086D\cell V\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;56\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 \cell 0x142D\cell Alt+0142\cell }{\ltrch\fcs1 
        '''\af123\afs12 \rtlch\fcs0 \ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines826_to_836() As String
            Get
                Return ResourceManager.GetString("lines826_to_836", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx3736\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx4140\clvertalt\clbrdrt\brdrnone \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines837_to_847() As String
            Get
                Return ResourceManager.GetString("lines837_to_847", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \f1\fs12\insrsid15886290 x255D\cell Alt+0255\cell }{\ltrch\fcs1 \af123\afs12 \rtlch\fcs0 \f142\fs12\lang1025\insrsid15886290\charrsid15886290 \&apos;ff\cell }\pard \ltrpar\ql \li0\ri0\widctlpar\intbl\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0 {
        '''\rtlch\fcs1 \af1 \ltrch\fcs0 \f1\insrsid15886290 \trowd \irow54\irowband54\ltrrow\ts11\trgaph108\trleft-108\trbrdrt\brdrs\brdrw10 \trbrdrl\brdrs\brdrw10 \trbrdrb\brdrs\brdrw10 \trbrdrr\brdrs\brdrw10 
        '''\trftsWidth1\trpaddl108\trpaddr108\trpaddfl3\trpaddfr3\t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines848_to_858() As String
            Get
                Return ResourceManager.GetString("lines848_to_858", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx8236\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx8640\row \ltrrow}\pard \ltrpar
        '''\ql \li0\ri0\nowidctlpar\intbl\wrapdefault\faauto\rin0\lin0 {\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f1\fs12\insrsid15886290 0x088D\cell X\cell }{\rtlch\fcs1 \af1\afs12 \ltrch\fcs0 \f123\fs12\insrsid15886290\charrsid15886290 \&apos;58\cell }{\rtlch\fcs1 
        '''\af1\afs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines859_to_869() As String
            Get
                Return ResourceManager.GetString("lines859_to_869", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx3736\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth404\clshdrawnil \cellx4140\clvertalt\clbrdrt\brdrnone \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrnone \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth262\clshdrawnil \cellx4402\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawni [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines870_to_880() As String
            Get
                Return ResourceManager.GetString("lines870_to_880", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx5207\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 
        '''\cltxlrtb\clftsWidth3\clwWidth805\clshdrawnil \cellx6012\clvertalt\clbrdrt\brdrs\brdrw15 \clbrdrl\brdrs\brdrw15 \clbrdrb\brdrs\brdrw15 \clbrdrr\brdrs\brdrw15 \cltxlrtb\clftsWidth3\clwWidth378\clshdrawnil \cellx6390\clvertalt\clbrdrt\brdrnone \clbrdrl
        '''\brdrs\brdrw15 \clbrdrb\brdrnone \clbrd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property lines89_to_99() As String
            Get
                Return ResourceManager.GetString("lines89_to_99", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033.
        '''</summary>
        Friend Shared ReadOnly Property Pretext_1() As String
            Get
                Return ResourceManager.GetString("Pretext_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\stylesheet{\ql \li0\ri0\widctlpar\wrapdefault\aspalpha\aspnum\faauto\adjustright\rin0\lin0\itap0 \rtlch\fcs1 \af0\afs24\alang1025 
        '''\ltrch\fcs0 \fs24\lang1033\langfe1033\cgrid\langnp1033\langfenp1033 \snext0 Normal;}
        '''{\*\cs10 \additive \ssemihidden Default Paragraph Font;}.
        '''</summary>
        Friend Shared ReadOnly Property Pretext_2() As String
            Get
                Return ResourceManager.GetString("Pretext_2", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
